spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/springbootdb
    username: root
    password: 1234
  h2:
    console:
      enabled: true

jwt:
  issuer: mightytonykr@gmail.com
  secret_key : study_springboot